-- 코드를 입력하세요
SELECT A.HISTORY_ID, 
    FLOOR((DATEDIFF(A.END_DATE, A.START_DATE)+1) * (B.DAILY_FEE-(B.DAILY_FEE /100*REPLACE(IFNULL(C.DISCOUNT_RATE,0),'%','')))) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
LEFT JOIN CAR_RENTAL_COMPANY_CAR AS B ON A.CAR_ID = B.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON B.CAR_TYPE = C.CAR_TYPE AND
    C.DURATION_TYPE = CASE 
         WHEN DATEDIFF(A.END_DATE, A.START_DATE)+1 >= 90 THEN '90일 이상'
         WHEN DATEDIFF(A.END_DATE, A.START_DATE)+1 >= 30 THEN '30일 이상'
         WHEN DATEDIFF(A.END_DATE, A.START_DATE)+1 >= 7 THEN '7일 이상'
         ELSE ''
         END

WHERE B.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC